"""Initiales Schema (Kapitel 6)

Revision ID: 3d3d5413138a
Revises: 
Create Date: 2026-07-30 13:42:16.598700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3d3d5413138a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('bank', sa.String(length=128), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('opening_balance_date', sa.Date(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_iban'), 'accounts', ['iban'], unique=False)
    op.create_table('bank_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('delimiter', sa.String(length=4), nullable=False),
    sa.Column('quotechar', sa.String(length=1), nullable=False),
    sa.Column('encoding', sa.String(length=32), nullable=False),
    sa.Column('skip_rows', sa.Integer(), nullable=False),
    sa.Column('header_signature', sa.String(length=128), nullable=False),
    sa.Column('column_map', sa.JSON(), nullable=False),
    sa.Column('date_formats', sa.JSON(), nullable=False),
    sa.Column('decimal_separator', sa.String(length=1), nullable=False),
    sa.Column('thousands_separator', sa.String(length=1), nullable=False),
    sa.Column('negate_amount', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_from', sa.String(length=3), nullable=False),
    sa.Column('currency_to', sa.String(length=3), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_from', 'currency_to', 'rate_date')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('account_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_id')
    )
    op.create_index(op.f('ix_account_roles_account_id'), 'account_roles', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_roles_user_id'), 'account_roles', ['user_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_fixed_cost', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_layouts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tiles', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('num_transactions', sa.Integer(), nullable=False),
    sa.Column('reverted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['bank_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('color_scheme', sa.String(length=32), nullable=False),
    sa.Column('dark_mode', sa.Boolean(), nullable=False),
    sa.Column('prefs', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cycle_months', sa.Integer(), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paying_account_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('prefinance_note', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['paying_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('text_contains', sa.String(length=255), nullable=False),
    sa.Column('counterparty_contains', sa.String(length=255), nullable=False),
    sa.Column('iban_equals', sa.String(length=34), nullable=False),
    sa.Column('booking_text_contains', sa.String(length=255), nullable=False),
    sa.Column('amount_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_priority'), 'rules', ['priority'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_ref', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('counterparty', sa.String(length=255), nullable=False),
    sa.Column('counterparty_iban', sa.String(length=34), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('booking_text', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('raw_line', sa.Text(), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_booking_date'), 'transactions', ['booking_date'], unique=False)
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_transactions_counterparty_iban'), 'transactions', ['counterparty_iban'], unique=False)
    op.create_index(op.f('ix_transactions_dedup_hash'), 'transactions', ['dedup_hash'], unique=False)
    op.create_index(op.f('ix_transactions_import_batch_id'), 'transactions', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_transactions_transfer_id'), 'transactions', ['transfer_id'], unique=False)
    op.create_table('transaction_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_splits_transaction_id'), 'transaction_splits', ['transaction_id'], unique=False)
    op.create_table('transaction_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'tag_id')
    )
    op.create_index(op.f('ix_transaction_tags_tag_id'), 'transaction_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_transaction_tags_transaction_id'), 'transaction_tags', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_tags_transaction_id'), table_name='transaction_tags')
    op.drop_index(op.f('ix_transaction_tags_tag_id'), table_name='transaction_tags')
    op.drop_table('transaction_tags')
    op.drop_index(op.f('ix_transaction_splits_transaction_id'), table_name='transaction_splits')
    op.drop_table('transaction_splits')
    op.drop_index(op.f('ix_transactions_transfer_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_import_batch_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_dedup_hash'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_counterparty_iban'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_booking_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_rules_priority'), table_name='rules')
    op.drop_table('rules')
    op.drop_table('recurring_items')
    op.drop_table('budgets')
    op.drop_table('user_settings')
    op.drop_table('import_batches')
    op.drop_table('dashboard_layouts')
    op.drop_table('categories')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_account_roles_user_id'), table_name='account_roles')
    op.drop_index(op.f('ix_account_roles_account_id'), table_name='account_roles')
    op.drop_table('account_roles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('transfers')
    op.drop_table('tags')
    op.drop_table('exchange_rates')
    op.drop_table('bank_profiles')
    op.drop_index(op.f('ix_accounts_iban'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
