"""v1.1: app_settings (Budget-Schwellwerte)

Revision ID: 4716bba51f85
Revises: 3d3d5413138a
Create Date: 2026-07-30 14:03:01.260071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4716bba51f85'
down_revision: Union[str, None] = '3d3d5413138a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
