"""v1.2: bank_balance, wiederkehrende Kostenpositionen, Vorfinanzierungs-Verknuepfung

Revision ID: 88074465d762
Revises: 4716bba51f85
Create Date: 2026-07-30 14:15:37.149029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '88074465d762'
down_revision: Union[str, None] = '4716bba51f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurring_item_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recurring_item_id'], ['recurring_items.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'role')
    )
    op.create_index(op.f('ix_recurring_links_recurring_item_id'), 'recurring_links', ['recurring_item_id'], unique=False)
    op.create_index(op.f('ix_recurring_links_transaction_id'), 'recurring_links', ['transaction_id'], unique=False)
    # Batch-Mode: SQLite (Entwicklung/Tests) unterstützt kein ALTER für
    # Fremdschlüssel-Constraints, PostgreSQL (Produktion) läuft darüber transparent hinweg.
    with op.batch_alter_table('recurring_items') as batch_op:
        batch_op.add_column(sa.Column('match_text', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('reimbursement_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reimbursement_match_text', sa.String(length=255), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('current_rate', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.create_foreign_key('fk_recurring_items_reimbursement_account_id', 'accounts',
                                    ['reimbursement_account_id'], ['id'])
    op.add_column('transactions', sa.Column('bank_balance', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'bank_balance')
    with op.batch_alter_table('recurring_items') as batch_op:
        batch_op.drop_constraint('fk_recurring_items_reimbursement_account_id', type_='foreignkey')
        batch_op.drop_column('current_rate')
        batch_op.drop_column('reimbursement_match_text')
        batch_op.drop_column('reimbursement_account_id')
        batch_op.drop_column('match_text')
    op.drop_index(op.f('ix_recurring_links_transaction_id'), table_name='recurring_links')
    op.drop_index(op.f('ix_recurring_links_recurring_item_id'), table_name='recurring_links')
    op.drop_table('recurring_links')
    # ### end Alembic commands ###
