"""v1.3: Kategorie-Flag is_transfer_like

Revision ID: f8812dff0959
Revises: 88074465d762
Create Date: 2026-08-04 20:24:52.107646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f8812dff0959'
down_revision: Union[str, None] = '88074465d762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default nötig, da die Tabelle in Produktion bereits Zeilen hat
    # (NOT NULL ohne Default lässt sich auf eine gefüllte Tabelle nicht anwenden)
    op.add_column('categories', sa.Column('is_transfer_like', sa.Boolean(),
                                          nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_transfer_like')
    # ### end Alembic commands ###
